### ISSUE TITLE
FR1: User Input Filter

### ISSUE THREAD

**Issue by MehediZihad** [WSU-4110/LaptopPicker#1]
|FR1.  User Input Filter|
|---|
|**Goal**: The system will give a suggestion to select what kind of they are initially interested..
**Stakeholders:** User|
| **Description:** When a user initially enters the website, they will receive a short list of questions asking: 1. Where did you hear about us? 2. What do you plan on using your laptop for: Personal, Business, Gaming, Other. 
| **Origin:** Based on initial project specification   document, team members came up with this description during the first   meeting.|
| **Version:** 1.0  |
|**Date:** 09/15/2022
|  **Priority:** 1 |

**Comment by blurple9999** [comment]
Combined with #14.
