### ISSUE TITLE
FR13: Sorting

### ISSUE THREAD

**Issue by MehediZihad** [WSU-4110/LaptopPicker#11]
|FR13: Sorting |
|---|
|**Goal**: Allow users to sort the list by category.
**Stakeholders:**  All User|
| **Description:**  While we offer a ton of filter options, thus making this feature a little bit unnecessary, it is still a staple of these kinds of sites, and many users would appreciate the ability to sort by a certain category, i.e. price. |
| **Origin:** Based on the initial project specification document, team members came up with this description during the first meeting. |
| **Version:** 1.0  |
|**Date:** 09/15/2022
|  **Priority:** 2 |

**Comment by blurple9999** [comment]
To more align with our goals of eliminating any biases towards a particular brand, the website will now by default sort from lowest to highest price, and remain that way.
