### ISSUE TITLE
FR5. Search Bar

### ISSUE THREAD

**Issue by anikarah** [WSU-4110/LaptopPicker#12]
|FR5.Search Bar|
|---|
|**Goal**: This bar goal is to make searches more efficient for customers.|
**Stakeholders:** User|
| **Description:** This will be available on the top of our website. This feature allows the user to enter a letter, word, database, or list of options that will return a list of options according to their search.. |
| **Origin:** After our second meeting we came through this description and we will make this service available to our customers.|
| **Version:** 1.0  |
|**Date:** 09/19/2022 |
|  **Priority:** 1|

**Comment by blurple9999** [comment]
Search bar has been implemented.
