### ISSUE TITLE
FR8: Recommended / Featured Products

### ISSUE THREAD

**Issue by sanjida-sultana** [WSU-4110/LaptopPicker#13]
|FR8: Recommended / Featured Products |
|---|
|**Goal**: Provide the best product recommendation.|
**Stakeholders:** Customers|
| **Description:** This feature allows customers to find the best product from our site. This feature will show the most functional laptop which is available on our site. This gives the list of good and most popular product lists.|
| **Origin:** In our second meeting after discussion we think this would be the one feature on our site to give customers a better experience.|
| **Version:** 1.0  |
|**Date:** 09/19/2022
|  **Priority:** 4 |

**Comment by blurple9999** [comment]
To further align with our ideas of a website with 0 biases, we have elected to omit this feature.
