### ISSUE TITLE
FR6. Product Filter Section

### ISSUE THREAD

**Issue by anikarah** [WSU-4110/LaptopPicker#14]
|FR6.Product Filter Section|
|---|
|**Goal**:The product filter section will give the user customized results..|
**Stakeholders:** User|
| **Description:** Users can filter for No. of RAM, CPU, Display category, price, and so on. By using the product filter section, users will find out more customized results with their specific needs. |
| **Origin:** Based on the initial project specification document, team members came up with this description during the first meeting.1|
| **Version:** 1.0  |
|**Date:** 09/15/2022 |
|  **Priority:** 1 |

**Comment by blurple9999** [comment]
This has been fully implemented.
