### ISSUE TITLE
FR14:Sign Up/Log In

### ISSUE THREAD

**Issue by MehediZihad** [WSU-4110/LaptopPicker#15]
|FR14: SignUp/Login |
|---|
|**Goal**: Secure user activities.
**Stakeholders:** All Users. |
| **Description:** When users open the website they have to signup first and have to log in to see all the laptop filtering and product pages. |
| **Origin:** Team members came up with this description during the second meeting.|
| **Version:** 1.0  |
|**Date:** 09/19/2022
|  **Priority:** 4 |

**Comment by sanjida-sultana** [comment]
Implemented this issue.
