### ISSUE TITLE
FR9: Favorite List

### ISSUE THREAD

**Issue by sanjida-sultana** [WSU-4110/LaptopPicker#16]
|FR9: Favorite List |
|---|
|**Goal**: The user can make a list according to the preferences and need |
**Stakeholders:** Customers|
| **Description:** Favorites are a unique way to go because instead of adding items to a specific list, users can quickly toggle something as one of their favorite items, immediately placing it in a separate "favorites" list. These items will remain on this list even after buying, making it incredibly useful to buy the same item over and over again.|
| **Origin:** Based on the initial project specification document, team members came up with this description during the first meeting.|
| **Version:** 1.0  |
|**Date:** 09/15/2022
|  **Priority:** 3 |

**Comment by blurple9999** [comment]
Favorites list has been implemented to the best of our ability, with the amount of time we have left.
