### ISSUE TITLE
FR15. List of Replacement Components

### ISSUE THREAD

**Issue by sanjida-sultana** [WSU-4110/LaptopPicker#18]
|FR15. List of Replacement Components |
|---|
|**Goal**: Have a list of replacement laptop components with similar filtering options. |
**Stakeholders:** Customers|
| **Description:**  For any of our users looking for a specific part to replace in their laptop, we can offer them the same main feature we advertise, but now with specific components, such as RAM, Storage, and potentially others, if given time.|
| **Origin:** Team members came up with this description during the second meeting.|
| **Version:** 1.0  |
|**Date:** 09/15/2022
|  **Priority:** 4 |

**Comment by blurple9999** [comment]
Not enough time to implement; lots of research involved with creating such a database. Webhost also has a database limit.
