### ISSUE TITLE
FR11. SQL Database

### ISSUE THREAD

**Issue by KANTA-00** [WSU-4110/LaptopPicker#19]
|FR11. SQL Database|
|---|
|**Goal**: Have a working SQL database of laptops/other components.
**Stakeholders:** All Users|
| **Description:** This is the key requirement that is needed for our website to function. This is where the list of laptops will go, as well as the SQL filtering rules. |
| **Origin:** Based on the initial project specification document, team members came up with this description during the first meeting.|
| **Version:** 1.0  |
|**Date:** 09/15/2022
|  **Priority:**  1|

**Comment by blurple9999** [comment]
The filter options are complete, and there are laptops in the database. More will be added, but this issue shall be considered complete.
