### ISSUE TITLE
FR2: Contact

### ISSUE THREAD

**Issue by MehediZihad** [WSU-4110/LaptopPicker#2]
|FR2:  Contact|
|---|
|**Goal**: The goal is to better understand the user. They are able to make contact with us.
**Stakeholders:** All User|
| **Description:** This is to better understand the user. If the user has any questions they can post.

| **Origin:** Based on the initial project specification document, team members came up with this description during the first meeting.|
| **Version:** 1.0  |
|**Date:** 09/15/2022
|  **Priority:** 3 |

**Comment by mehedizihad** [comment]
We Implement Contact page. It works perfectly.

**Comment by MehediZihad** [comment]
We Implement Contact page. It works perfectly.
