### ISSUE TITLE
FR12. Customer Website Rating

### ISSUE THREAD

**Issue by KANTA-00** [WSU-4110/LaptopPicker#20]
|FR12. Customer Website Rating|
|---|
|**Goal**:  Measure Customer satisfaction.
**Stakeholders:** All Users|
| **Description:** This is the opportunity for customers to rate their shopping experience with our website, usually after they've made a purchase with that website. These "votes" (usually one to five stars) are then aggregated and averaged to determine the overall rating for the products. This rating is then shown alongside the product information to help future customers make purchase decisions. |
| **Origin:** Based on the initial project specification document, team members came up with this description during the first meeting.|
| **Version:** 1.0  |
|**Date:** 09/15/2022
|  **Priority:** 1 |

**Comment by blurple9999** [comment]
Reworked into contact page, which is complete.
