### ISSUE TITLE
NFR2. Performance

### ISSUE THREAD

**Issue by blurple9999** [WSU-4110/LaptopPicker#4]
| NFR2. Performance |
|---|
| **Goal**: Have the filtered list ready quickly. |
| **Stakeholders:** User |
| **Description:** If it takes too long for a list to display after setting filter options, it can be infuriating trying to navigate to what you are looking for. |
| **Origin:** Team members came up with this description during the first meeting. |
| **Version:** 1.0  |
| **Date:** 09/11/2022 |
| **Priority:** 2 |

**Comment by sanjida-sultana** [comment]
Making the about Us page we tried to explain our goal and the reason why we made this website. This issue had done implemented.

**Comment by blurple9999** [comment]
Filter query goes through pretty much in an instant.
