### ISSUE TITLE
NFR4. Security

### ISSUE THREAD

**Issue by blurple9999** [WSU-4110/LaptopPicker#6]
| NFR4. Security |
|---|
| **Goal**: Keep database uncompromised. |
| **Stakeholders:** User |
| **Description:** The database can be open to attacks if we are not careful. Need to implement security checks to make sure no user will commit any malicious activity. |
| **Origin:** Team members came up with this description during the first meeting. |
| **Version:** 1.0  |
| **Date:** 09/11/2022 |
| **Priority:** 1 |

**Comment by sanjida-sultana** [comment]
making a hash database for passwords we keep our user information safe and secure nobody is able to see the user password because that is encrypted.
