### ISSUE TITLE
FR3. Deals & Promotions

### ISSUE THREAD

**Issue by anikarah** [WSU-4110/LaptopPicker#8]
|FR3. Deals & Promotions |
|---|
|**Goal**: The goal for this is to allow the user an option to see available and current deals and promotions. |
**Stakeholders:** User|
| **Description:** The website will have a section where they are able to browse current deals that are connected through the deals from the laptop vendors we will include. For example, if Amazon is having a lightning deal, that will show on the user's end for our website and include the promotions or deals a specific product or brand is having. . |
| **Origin:** Based on the initial project specification document, team members came up with this description during the first meeting.|
| **Version:** 1.0  |
|**Date:** 09/15/2022 |
|  **Priority:** 3 |

**Comment by blurple9999** [comment]
To further align with our ideas of a website with 0 biases, we have elected to omit this feature.
