### ISSUE TITLE
FR7:Browse All Products

### ISSUE THREAD

**Issue by sanjida-sultana** [WSU-4110/LaptopPicker#9]
|FR7. Browse All Products |
|---|
|**Goal**:   Help to find all products within less time.|
**Stakeholders:** Customers|
| **Description:** With this feature, people could search for a specific laptop according to their need, If the product is not available on our website, it will show the result not available.|
| **Origin:** According to our project specification we came up with this functional requirement.|
| **Version:** 1.0  |
|**Date:** 09/15/2022
|  **Priority:** 1 |

**Comment by blurple9999** [comment]
Fully implemented
